### ISSUE TITLE
better way to input ingredients

### ISSUE THREAD

**Issue by shiyingzheng** [shiyingzheng/recipe_search#50]
Currently the user has to use the right delimiter to get the ingredients to work. Once we implement units, we need to have a better way to input ingredients and amount.

**Comment by shiyingzheng** [comment]
blocked by #16

**Comment by shiyingzheng** [comment]
Unblocked. #16 is implemented. Now we could work on the front end changes for this if we have time.

**Comment by ColePeppis** [comment]
My new branch ingredient_input fixes this!
