### ISSUE TITLE
Need to set up admin account on Heroku

### ISSUE THREAD

**Issue by shiyingzheng** [shiyingzheng/recipe_search#55]
We will need to do this before prepping for the presentation, so that we can more easily manage the content we are going to present. 

Other than that it also would be useful to edit recipes if a user reports something wrong with a recipe to the admin. This is relevant to #37.

**Comment by shangwyoung** [comment]
I just did it!
username: **********
password: ***********

To run commands on heroku, type in terminal:
1. heroku login (to set things up)
[login with credentials]
2. heroku run <python command> --app <app name>
